[package]
name = "playlist-localizer"
version = "0.3.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "3.0.0-rc.8", features = ["wrap_help", "cargo"] }
clap_generate = "3.0.0-rc.8"
id3 = "0.6.6"
mp4ameta = "0.11.0"
walkdir = "2.3.2"
