[package]
name = "playlist_localizer"
version = "0.3.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
id3 = "0.6.2"
mp4ameta = "0.9.1"
walkdir = "2.3.1"
