[package]
name = "playlist_localizer"
version = "0.2.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2018"

[dependencies]
walkdir = "2.3.1"
clap = "2.33.1"
id3 = "0.5.1"
mp4ameta = "0.3.0"
