[package]
name = "playlist-localizer"
version = "0.3.0"
authors = ["Saecki <tobiasschmitz2001@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.5.31", features = ["wrap_help", "cargo"] }
clap_complete = "4.5.46"
id3 = { version = "1.16.2", default-features = false }
mp4ameta = "0.12.1"
walkdir = "2.5.0"
